import { AcalaTokenType } from "./types";

const supported: AcalaTokenType[] = [
  {
    name: "Karura",
    symbol: "KAR",
    decimals: 12,
    image: require("./icons/KAR.svg"),
    coingeckoID: "acala",
    native: true,
  },
  {
    name: "Acala Dollar",
    symbol: "AUSD",
    decimals: 12,
    image: require("./icons/AUSD.png"),
    coingeckoID: "usd-coin",
  },
  {
    name: "Kusama",
    symbol: "KSM",
    decimals: 12,
    image: require("./icons/KSM.png"),
    coingeckoID: "kusama",
  },
  {
    name: "Liquid KSM",
    symbol: "LKSM",
    decimals: 12,
    image: require("./icons/LKSM.png"),
    coingeckoID: "kusama",
  },
  {
    name: "Bifrost",
    symbol: "BNC",
    decimals: 12,
    image: require("./icons/BNC.png"),
    coingeckoID: "bifrost-native-coin",
  },
  {
    name: "Kintsugi",
    symbol: "KINT",
    decimals: 12,
    image: require("./icons/KINT.png"),
    coingeckoID: "kintsugi",
  },
  {
    name: "Phala",
    symbol: "PHA",
    decimals: 12,
    image: require("./icons/PHA.png"),
    coingeckoID: "pha",
  },
  {
    name: "Crab",
    symbol: "CRAB",
    decimals: 18,
    image: require("./icons/CRAB.png"),
    foreignAssetId: 13,
    coingeckoID: "darwinia-crab-network-native-token",
  },
  {
    name: "Crust Shadow",
    symbol: "CSM",
    decimals: 12,
    image: require("./icons/CSM.png"),
    foreignAssetId: 5,
    coingeckoID: "crust-shadow",
  },
  {
    name: "Genshiro",
    symbol: "GEN",
    decimals: 9,
    image: require("./icons/GENS.png"),
    foreignAssetId: 14,
    coingeckoID: "genshiro",
  },
  {
    name: "Kintsugi BTC",
    symbol: "KBTC",
    decimals: 8,
    image: require("./icons/KBTC.png"),
    coingeckoID: "bitcoin",
  },
  {
    name: "Calamari",
    symbol: "KMA",
    decimals: 12,
    image: require("./icons/KMA.png"),
    foreignAssetId: 10,
    coingeckoID: "calamari-network",
  },
  {
    name: "Moonriver",
    symbol: "MOVR",
    decimals: 18,
    image: require("./icons/MOVR.png"),
    foreignAssetId: 3,
    coingeckoID: "moonriver",
  },
  {
    name: "Quartz",
    symbol: "QTZ",
    decimals: 18,
    image: require("./icons/QTZ.png"),
    foreignAssetId: 2,
    coingeckoID: "quartz",
  },
  {
    name: "Integritee",
    symbol: "TEER",
    decimals: 12,
    image: require("./icons/TEER.png"),
    foreignAssetId: 8,
    coingeckoID: "integritee",
  },
  {
    name: "USD Coin",
    symbol: "USDC",
    decimals: 6,
    image: require("./icons/USDC.png"),
    erc20Address: "0x1f3a10587a20114ea25ba1b388ee2dd4a337ce27",
    coingeckoID: "usd-coin",
  },
  {
    name: "Tether",
    symbol: "USDT",
    decimals: 6,
    image: require("./icons/USDT.png"),
    foreignAssetId: 7,
    coingeckoID: "tether",
  },
  {
    name: "Altair",
    symbol: "AIR",
    decimals: 18,
    image: require("./icons/AIR.png"),
    foreignAssetId: 12,
    coingeckoID: "altair",
  },
  {
    name: "PolarisDAO",
    symbol: "ARIS",
    decimals: 8,
    image: require("./icons/ARIS.png"),
    foreignAssetId: 1,
  },
  {
    name: "Turing",
    symbol: "TUR",
    decimals: 10,
    image: require("./icons/TUR.png"),
    foreignAssetId: 16,
  },
  {
    name: "Metaverse.Network",
    symbol: "NEER",
    decimals: 18,
    image: require("./icons/NEER.png"),
    foreignAssetId: 9,
  },
  {
    name: "Kico",
    symbol: "KICO",
    decimals: 14,
    image: require("./icons/KICO.png"),
    foreignAssetId: 6,
  },
  {
    name: "Heiko",
    symbol: "HKO",
    decimals: 12,
    image: require("./icons/HKO.png"),
    foreignAssetId: 4,
  },
  {
    name: "RMRK",
    symbol: "RMRK",
    decimals: 10,
    image: require("./icons/RMRK.png"),
    foreignAssetId: 0,
    coingeckoID: "rmrk",
  },
  {
    name: "Basilisk",
    symbol: "RSX",
    decimals: 12,
    image: require("./icons/BSX.png"),
    foreignAssetId: 12,
  },
  {
    name: "Taiga",
    symbol: "TAI",
    decimals: 12,
    image: require("./icons/TAI.png"),
  },
  {
    name: "Taiga KSM",
    symbol: "taiKSM",
    decimals: 12,
    image: require("./icons/taiKSM.png"),
    stableAssetId: 0,
    coingeckoID: "kusama",
  },
];
export default supported;
