export enum NetworkNames {
  Ethereum = "ETH",
  Binance = "BNB",
  EthereumClassic = "ETC",
  Goerli = "GOERLI",
  Kovan = "KOV",
  Matic = "MATIC",
  Moonbeam = "GLMR",
  Rinkeby = "RIN",
  Ropsten = "ROP",
  Acala = "ACA",
  Karura = "KAR",
  Kusama = "KSM",
  Polkadot = "DOT",
}
