export enum NetworkNames {
  Ethereum = "ETH",
  Binance = "BNB",
  EthereumClassic = "ETC",
  Goerli = "GOERLI",
  Kovan = "KOV",
  Matic = "MATIC",
  Moonbeam = "GLMR",
  Moonriver = "MOVR",
  Rinkeby = "RIN",
  Ropsten = "ROP",
  Acala = "ACA",
  Karura = "KAR",
  KaruraEVM = "evmKAR",
  Kusama = "KSM",
  Polkadot = "DOT",
  Westend = "WND",
  Bitcoin = "BTC",
}
