export enum NetworkNames {
  Ethereum = "ETH",
  Binance = "BNB",
  EthereumClassic = "ETC",
  Goerli = "GOERLI",
  Kovan = "KOV",
  Matic = "MATIC",
  Moonbeam = "GLMR",
  Moonriver = "MOVR",
  Rinkeby = "RIN",
  Ropsten = "ROP",
  Acala = "ACA",
  Karura = "KAR",
  KaruraEVM = "evmKAR",
  Kusama = "KSM",
  Polkadot = "DOT",
  Westend = "WND",
  Bitcoin = "BTC",
  BitcoinTest = "BTCTest",
}

export enum CoingeckoPlatform {
  Ethereum = "ethereum",
  Binance = "binance-smart-chain",
  EthereumClassic = "ethereum-classic",
  Matic = "polygon-pos",
  Moonbeam = "moonbeam",
  Moonriver = "moonriver",
  Acala = "acala",
  Karura = "karura",
  KaruraEVM = "karura",
  Kusama = "kusama",
  Polkadot = "polkadot",
}
