import { Resolution } from "@unstoppabledomains/resolution";
import { BaseResolver, CoinType } from "../types";
import { getTLD } from "../utils";

class UDResolver implements BaseResolver {
  UDProvider: Resolution;

  name: string;

  supportedTLDs = [
    "888",
    "academy",
    "actor",
    "agency",
    "ai",
    "altimist",
    "anime",
    "app",
    "archi",
    "army",
    "art",
    "ask",
    "associates",
    "austin",
    "bald",
    "band",
    "bargains",
    "basenji",
    "bay",
    "bch",
    "bet",
    "bike",
    "binanceus",
    "bio",
    "bitcoin",
    "bitget",
    "bitscrunch",
    "biz",
    "black",
    "blockchain",
    "blue",
    "bobi",
    "boo",
    "boomer",
    "boston",
    "bot",
    "boutique",
    "brave",
    "broker",
    "ca",
    "calicoin",
    "care",
    "cash",
    "casino",
    "caw",
    "cc",
    "center",
    "channel",
    "chat",
    "cheap",
    "chomp",
    "church",
    "city",
    "claims",
    "clay",
    "club",
    "co",
    "codes",
    "coffee",
    "com",
    "company",
    "computer",
    "consulting",
    "cool",
    "coupons",
    "credit",
    "crypto",
    "dad",
    "dance",
    "dao",
    "dating",
    "day",
    "deal",
    "dejay",
    "delivery",
    "depin",
    "derad",
    "design",
    "dev",
    "dfz",
    "digital",
    "direct",
    "directory",
    "doctor",
    "doga",
    "donut",
    "dream",
    "email",
    "emir",
    "energy",
    "engineering",
    "enterprises",
    "esq",
    "estate",
    "eth",
    "ethermail",
    "events",
    "exchange",
    "express",
    "family",
    "farm",
    "finance",
    "financial",
    "fitness",
    "foo",
    "forex",
    "forsale",
    "free",
    "fun",
    "furniture",
    "fyi",
    "games",
    "global",
    "go",
    "gold",
    "golf",
    "group",
    "grow",
    "guru",
    "haus",
    "hegecoin",
    "her",
    "hi",
    "hiphop",
    "hockey",
    "host",
    "hot",
    "house",
    "how",
    "hub",
    "info",
    "ing",
    "institute",
    "international",
    "investments",
    "io",
    "irish",
    "kim",
    "kingdom",
    "kitchen",
    "klever",
    "kresus",
    "kryptic",
    "land",
    "lfg",
    "lgbt",
    "life",
    "link",
    "live",
    "llc",
    "loans",
    "ltc",
    "ltd",
    "manga",
    "markets",
    "mba",
    "me",
    "media",
    "meme",
    "mery",
    "metropolis",
    "miami",
    "miku",
    "ministry",
    "mobi",
    "moi",
    "money",
    "moon",
    "mov",
    "movie",
    "mumu",
    "mycircle",
    "net",
    "network",
    "new",
    "news",
    "nexus",
    "nft",
    "nibi",
    "ninja",
    "now",
    "npc",
    "og",
    "onchain",
    "online",
    "org",
    "organic",
    "page",
    "partners",
    "parts",
    "pastor",
    "pendle",
    "pengu",
    "pet",
    "phd",
    "photography",
    "photos",
    "pink",
    "pizza",
    "plus",
    "podcast",
    "pog",
    "poker",
    "polygon",
    "press",
    "privacy",
    "pro",
    "productions",
    "prof",
    "promo",
    "properties",
    "propykeys",
    "pudgy",
    "pw",
    "quantum",
    "rad",
    "raiin",
    "recipes",
    "red",
    "rentals",
    "repair",
    "report",
    "restaurant",
    "retardio",
    "rip",
    "rocks",
    "rsvp",
    "run",
    "sale",
    "secret",
    "services",
    "show",
    "singles",
    "site",
    "ski",
    "smobler",
    "social",
    "software",
    "solutions",
    "sonic",
    "south",
    "soy",
    "space",
    "spot",
    "stepn",
    "store",
    "studio",
    "style",
    "support",
    "swamp",
    "systems",
    "tax",
    "taxi",
    "tball",
    "tea",
    "team",
    "tech",
    "technology",
    "tips",
    "today",
    "tools",
    "town",
    "toys",
    "training",
    "tribe",
    "twin",
    "u",
    "ubu",
    "uno",
    "unstoppable",
    "video",
    "vin",
    "vip",
    "vote",
    "voto",
    "wallet",
    "watch",
    "watches",
    "website",
    "wif",
    "wifi",
    "wine",
    "witg",
    "work",
    "works",
    "world",
    "wrkx",
    "wtf",
    "x",
    "xec",
    "xmr",
    "xyo",
    "xyz",
    "zil",
    "zip",
    "zone",
  ];

  constructor() {
    this.UDProvider = new Resolution({
      sourceConfig: {
        uns: {
          locations: {
            Layer1: {
              url: "https://nodes.mewapi.io/rpc/eth",
              network: "mainnet",
            },
            Layer2: {
              url: "https://nodes.mewapi.io/rpc/matic",
              network: "polygon-mainnet",
            },
          },
        },
      },
    });
    this.name = "ud";
  }

  // eslint-disable-next-line class-methods-use-this, @typescript-eslint/no-empty-function
  public async init(): Promise<void> {}

  public async resolveReverseName(address: string): Promise<string | null> {
    return this.UDProvider.reverse(address)
      .then((name) => name)
      .catch(() => null);
  }

  public async resolveAddress(
    name: string,
    coin: CoinType = "ETH",
  ): Promise<string | null> {
    return this.UDProvider.addr(name, coin)
      .then((address) => address)
      .catch(() => null);
  }

  public isSupportedName(name: string): boolean {
    return this.supportedTLDs.includes(getTLD(name));
  }
}

export default UDResolver;
